### ISSUE TITLE
Two outputs - is it possible?

### ISSUE THREAD

**Issue by Muldbak** [fabiodimarco/torch-levenberg-marquardt#1]
I would like to make a NN that estimates two seperate outputs, but I unfortunately get this error when trying to do so:

\torch_levenberg_marquardt\training.py", line 421, in training_step
    JJ = J.t() @ J  # JJ = J' * J
         ^^^^^
RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

Is there a way to combat this in some way shape or form? I've attached my current attempt as a ZIP, where i started from your own example and some mock data:
[LM_test_issue.zip](https://github.com/user-attachments/files/18195722/LM_test_issue.zip)

Thanks for the work you've put into making LM available for both Torch and TF!

**Comment by fabiodimarco** [comment]
Hi @Muldbak, thanks for reporting it. I actually fixed this bug yesterday, but I hadn’t updated the version on PyPI until now. Please try out version 1.1.3 and let me know if it resolves the issue. It seems to work fine on my end.

**Comment by Muldbak** [comment]
Thanks for the reply @fabiodimarco, it works like a charm in 1.1.3!

**Comment by fabiodimarco** [comment]
Perfect, thanks! I close the issue then.
